version: 2.1

workflows:
  build-deploy:
    jobs:
      - torch-arm64

jobs:
  torch-arm64:
    machine:
      image: cimg/base:stable
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker buildx build \
          --platform=linux/arm64 \
          --progress=plain \
          --output type=local,dest=. \
          --file Dockerfile .
      - store_artifacts:
          path: /torch.tar
          destination: torch.tar