name: ci

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build_wheels:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v2
          
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
          
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        
        - name: Cache Docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-
        
        - name: Build Docker Image
          run: |
            docker buildx build \
              --platform=linux/arm64 \
              --progress=plain \
              --output type=local,dest=./wheels \
              --file Dockerfile .

        - name: Upload Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: wheels
            path: |
              wheels/*.whl

        # This ugly bit is necessary if you don't want your cache to grow forever
        # till it hits GitHub's limit of 5GB.
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        - name: Move cache
          run: |
            rm -rf /tmp/.buildx-cache
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache